import { useCallback } from "react";
import { useNavigate } from "react-router-dom";
import TopBar from "../components/TopBar";
import LoginScreen1 from "../components/LoginScreen1";
import Calendar from "../components/Calendar";

const OrgOrganizeEventPage1 = () => {
  const navigate = useNavigate();

  const onFrameButton1Click = useCallback(() => {
    navigate("/org-organize-event-page-3");
  }, [navigate]);

  return (
    <div className="w-full relative [background:linear-gradient(112.9deg,_#bdbdbd_12%,_#808080)] h-[832px] overflow-hidden flex flex-col items-center justify-start text-center text-29xl text-black font-poppins">
      <TopBar
        signIn="Organize"
        signIn1="Events"
        signIn2="About Us"
        frameButtonGap="400px"
      />
      <div className="overflow-hidden flex flex-row items-center justify-start pt-14 pb-10 pr-[90px] pl-[57px] gap-[66px]">
        <LoginScreen1
          wereSoExcitedToSeeYouAgai="What would you like to "
          hide="Name"
          text="Hide"
          text1="Error message"
          forgetYourPassword="Text"
          signUp="Don’t have an acount? "
          showFrameArticle={false}
          passwordHideSee
          showTextField={false}
          errorMessage1
          frameArticleVisible={false}
          passwordHideSee1
          showIcon={false}
          errorMessage3
          showText={false}
          showFrameButton={false}
          showDontHaveAn={false}
          loginScreenHeight="612px"
          loginScreenBorderRadius="15px"
          loginScreenBackgroundColor="#fff"
          loginScreenBoxShadow="2px 2px 15px 4px rgba(0, 0, 0, 0.25)"
          loginScreenPadding="0px 30px"
          loginScreenPosition="unset"
          loginScreenTop="unset"
          loginScreenLeft="unset"
          loginScreenWidth="unset"
          frameDivAlignSelf="unset"
          wereSoExcitedMargin="0"
          wereSoExcitedPosition="unset"
          wereSoExcitedFontSize="unset"
          wereSoExcitedFontWeight="unset"
          wereSoExcitedFontFamily="unset"
          wereSoExcitedColor="unset"
          wereSoExcitedTextAlign="unset"
          wereSoExcitedDisplay="unset"
          wereSoExcitedAlignSelf="unset"
          loginWidth="unset"
          loginPosition="unset"
          loginHeight="unset"
          loginMargin="0"
          loginAlignSelf="unset"
          frameArticlePosition="relative"
          frameArticleHeight="unset"
          frameArticleWidth="409px"
          frameArticleTop="unset"
          frameArticleRight="unset"
          frameArticleBottom="unset"
          frameArticleLeft="unset"
          frameArticleMargin="0"
          frameArticleFontSize="24px"
          frameArticleFontWeight="400"
          frameArticleFontFamily="Poppins"
          frameArticleColor="#666"
          frameArticleTextAlign="center"
          labelPosition="unset"
          labelTop="unset"
          labelLeft="unset"
          labelFontSize="unset"
          labelFontFamily="unset"
          labelColor="unset"
          labelTextAlign="unset"
          labelDisplay="flex"
          labelFlexDirection="column"
          labelGap="32px"
          passwordHideSeePosition="relative"
          passwordHideSeeTop="unset"
          passwordHideSeeRight="unset"
          passwordHideSeeWidth="484px"
          passwordHideSeeHeight="87px"
          iconTop="0%"
          iconRight="0%"
          iconWidth="100%"
          iconHeight="31.03%"
          iconOverflow="unset"
          iconBottom="68.97%"
          iconLeft="0%"
          hideRight="unset"
          hideColor="#666"
          hideTextAlign="left"
          hideLeft="0px"
          textFieldBorder="unset"
          textFieldOutline="unset"
          textFieldBackgroundColor="unset"
          textFieldHeight="27px"
          textFieldWidth="73px"
          textFieldTop="0px"
          textFieldRight="8.9px"
          textFieldBottom="unset"
          textFieldLeft="unset"
          textFieldBorderRadius="unset"
          textFieldOverflow="unset"
          errorMessageTop="3px"
          errorMessageLeft="unset"
          errorMessageFontSize="unset"
          errorMessageFontFamily="unset"
          errorMessageColor="unset"
          errorMessageTextAlign="unset"
          errorMessageRight="49px"
          errorMessageWidth="24px"
          errorMessageHeight="24px"
          errorMessageOverflow="hidden"
          textHeight="unset"
          textWidth="unset"
          textTop="0px"
          textLeft="unset"
          textColor="rgba(102, 102, 102, 0.8)"
          textTextAlign="right"
          textRight="0px"
          loginWidth1="100%"
          loginPosition1="absolute"
          loginHeight1="64.37%"
          loginBorder="1px solid rgba(102, 102, 102, 0.35)"
          loginOutline="none"
          loginBackgroundColor="transparent"
          loginTop="35.63%"
          loginRight="0%"
          loginBottom="0%"
          loginLeft="0%"
          loginBorderRadius="12px"
          loginOverflow="hidden"
          loginAlignSelf1="unset"
          frameArticleHeight1="unset"
          frameArticleWidth1="unset"
          frameArticleTop1="104.6%"
          frameArticleRight1="unset"
          frameArticleBottom1="unset"
          frameArticleFontSize1="14px"
          frameArticleFontFamily1="Poppins"
          frameArticleColor1="#ee1d52"
          frameArticleTextAlign1="left"
          labelTop1="35.63%"
          labelLeft1="1.86%"
          labelColor1="rgba(255, 255, 255, 0)"
          labelTextAlign1="center"
          labelHeight="65.52%"
          labelWidth="97.52%"
          passwordMargin="unset"
          passwordWidth="484px"
          passwordPosition="relative"
          passwordHeight="87px"
          passwordHideSeeRight1="unset"
          passwordHideSeeWidth1="unset"
          passwordHideSeeHeight1="unset"
          passwordHideSeeLeft="0px"
          passwordHideSeeFontSize="16px"
          passwordHideSeeFontFamily="Poppins"
          passwordHideSeeColor="#666"
          passwordHideSeeTextAlign="left"
          iconRight1="8.9px"
          iconWidth1="73px"
          iconOverflow1="unset"
          hideRight1="49px"
          hideFontSize="unset"
          hideFontFamily="unset"
          hideColor1="unset"
          hideTextAlign1="unset"
          hideDisplay="unset"
          hideWidth="24px"
          hideHeight="24px"
          hideOverflow="hidden"
          textFieldBorder1="unset"
          textFieldOutline1="unset"
          textFieldBackgroundColor1="unset"
          textFieldHeight1="unset"
          textFieldWidth1="unset"
          textFieldTop1="0px"
          textFieldRight1="0px"
          textFieldBottom1="unset"
          textFieldLeft1="unset"
          textFieldBorderRadius1="unset"
          textFieldOverflow1="unset"
          textFieldFontSize="18px"
          textFieldFontFamily="Poppins"
          textFieldColor="rgba(102, 102, 102, 0.8)"
          textFieldTextAlign="right"
          textFieldDisplay="inline-block"
          errorMessageTop1="35.63%"
          errorMessageFontSize1="unset"
          errorMessageFontFamily1="unset"
          errorMessageColor1="unset"
          errorMessageTextAlign1="unset"
          errorMessageBorder="1px solid rgba(102, 102, 102, 0.35)"
          errorMessageOutline="none"
          errorMessageBackgroundColor="transparent"
          errorMessageHeight1="64.37%"
          errorMessageWidth1="100%"
          errorMessageRight1="0%"
          errorMessageBottom="0%"
          errorMessageBorderRadius="12px"
          errorMessageOverflow1="hidden"
          textHeight1="unset"
          textWidth1="unset"
          textTop1="104.6%"
          textLeft1="0%"
          textColor1="#ee1d52"
          textTextAlign1="left"
          forgetYourPasswordBorder="unset"
          forgetYourPasswordPadding="unset"
          forgetYourPasswordBackgroundColor="unset"
          forgetYourPasswordPosition="absolute"
          forgetYourPasswordTextDecoration="unset"
          forgetYourPasswordFontWeight="unset"
          forgetYourPasswordColor="rgba(255, 255, 255, 0)"
          forgetYourPasswordTextAlign="center"
          forgetYourPasswordHeight="65.52%"
          forgetYourPasswordWidth="97.52%"
          forgetYourPasswordTop="35.63%"
          forgetYourPasswordLeft="1.86%"
          frameButtonBackgroundColor="transparent"
          frameButtonWidth="184px"
          frameButtonBorderRadius="unset"
          frameButtonHeight="unset"
          frameButtonOverflow="unset"
          frameButtonFontSize="16px"
          frameButtonTextDecoration="underline"
          frameButtonFontWeight="500"
          frameButtonFontFamily="Poppins"
          frameButtonColor="#111"
          frameButtonTextAlign="left"
          frameButtonAlignSelf="unset"
          logInPosition="relative"
          logInTop="unset"
          logInLeft="unset"
          logInFontSize="unset"
          logInFontWeight="unset"
          logInFontFamily="unset"
          logInColor="unset"
          logInTextAlign="unset"
          logInDisplay="unset"
          logInBorder="none"
          logInPadding="0"
          logInBackgroundColor="#111"
          logInBorderRadius="32px"
          logInOverflow="hidden"
          alreadyHaveAnContainerBorder="unset"
          alreadyHaveAnContainerPadding="unset"
          alreadyHaveAnContainerBackgroundColor="unset"
          alreadyHaveAnContainerPosition="absolute"
          alreadyHaveAnContainerFontSize="22px"
          alreadyHaveAnContainerTextAlign="center"
          alreadyHaveAnContainerDisplay="flex"
          alreadyHaveAnContainerTop="calc(50% - 32px)"
          alreadyHaveAnContainerLeft="calc(50% - 242px)"
          alreadyHaveAnContainerFontWeight="500"
          alreadyHaveAnContainerFontFamily="Poppins"
          alreadyHaveAnContainerColor="#666"
          alreadyHaveAnContainerWidth="484px"
          alreadyHaveAnContainerHeight="64px"
          dontHaveAnFontFamily="unset"
          dontHaveAnColor="unset"
          dontHaveAnBorder="none"
          dontHaveAnPadding="0"
          dontHaveAnBackgroundColor="transparent"
          dontHaveAnWidth="246px"
          dontHaveAnPosition="relative"
          dontHaveAnFontSize="16px"
          dontHaveAnTextAlign="left"
          signUpTextDecoration="unset"
          signUpFontWeight="unset"
          signUpColor="#666"
          onFrameButton1Click={onFrameButton1Click}
          showPassword={false}
          passwordHideSee2
          showHide={false}
          errorMessage11={false}
          passwordHideSee11={false}
          showHide1
          errorMessage111={false}
        />
        <div className="rounded-mini bg-white shadow-[2px_2px_15px_4px_rgba(0,_0,_0,_0.25)] overflow-hidden flex flex-col items-start justify-start p-[30px] gap-[20px]">
          <div className="w-[430px] relative h-[166px]">
            <div className="absolute top-[0px] left-[0px] bg-white shadow-[4px_4px_4px_rgba(0,_0,_0,_0.25)] box-border w-[430px] h-[166px] border-[2px] border-solid border-gray-4" />
            <b className="absolute top-[16px] left-[49px] flex items-center justify-center w-[331px] h-[133px]">
              March 11th
            </b>
          </div>
          <Calendar
            dateBoxShadow="4px 4px 4px rgba(0, 0, 0, 0.25)"
            dateBorder="2px solid #bdbdbd"
          />
        </div>
      </div>
    </div>
  );
};

export default OrgOrganizeEventPage1;
